### PR TITLE
Add Authorization support

### PR DESCRIPTION
**Pull request by gaoqiangz**
增加`Authorization`支持

### 相关文档
1) https://www.apolloconfig.com/#/zh/usage/other-language-client-user-guide?id=_15-%e9%85%8d%e7%bd%ae%e8%ae%bf%e9%97%ae%e5%af%86%e9%92%a5
2) https://github.com/apolloconfig/apollo/blob/aa184a2e11d6e7e3f519d860d69f3cf30ccfcf9c/apollo-core/src/main/java/com/ctrip/framework/apollo/core/signature/Signature.java

### CODE REVIEW

**Comment by jmjoy** [comment]
改了些东西，帮忙看看 https://github.com/gaoqiangz/apollo-client/pull/1

**Comment by jmjoy** [comment]
CI的问题，能否修一下呢？

**Comment by gaoqiangz** [comment]
修了

**Comment by jmjoy** [comment]
已发版 <https://crates.io/crates/apollo-client>

**Pull request merged**
